config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  # blogs
  resources :blogs
  get "myblogs", as: "blogs/myblogs", to: "blogs#myblogs"

  # Users
  resources :users, only: [ :show ]
  delete "cancel_account", to: "users#cancel_account", as: :cancel_account

  # Admin panel
  namespace :admin do
    get "dashboard", to: "dashboard#index"

    resources :users, only: [ :index, :destroy ] do
      member do
        patch :toggle_role
        get :confirm_destroy
        delete :destroy_with_password
      end
    end
  end

  # comments
  resources :blogs do
    resources :comments, only: [:create]
  end

  # health  check and root
  get "up" => "rails/health#show", as: :rails_health_check
  root "blogs#index"
end

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "HomePage", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="navbar-text me-3">Welcome, <%= current_user.email %></span>
          </li>
          <li class="nav-item">
            <%= link_to "Blogs", blogs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>