config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  # blogs
  resources :blogs
  get "myblogs", as: "blogs/myblogs", to: "blogs#myblogs"

  # Users
  resources :users, only: [ :show ]
  delete "cancel_account", to: "users#cancel_account", as: :cancel_account

  # Admin panel
  namespace :admin do
    get "dashboard", to: "dashboard#index"

    resources :users, only: [ :index, :destroy ] do
      member do
        patch :toggle_role
        get :confirm_destroy
        delete :destroy_with_password
      end
    end
  end

  # comments
  resources :blogs do
    resources :comments, only: [:create]
  end

  # health  check and root
  get "up" => "rails/health#show", as: :rails_health_check
  root "blogs#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start mt-5 border-top py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-md-start mb-2 mb-md-0">
        <span class="text-muted">&copy; 2025 ThreadHub</span>
      </div>
      <div class="col-md-6 text-md-end">
        <a href="https://portfolio-3c9553.gitlab.io/en/" class="text-muted text-decoration-none me-3"target="_blank" title="Portfolio">Portfolio</a>
        <a href="https://gitlab.com/javier.beltran.hmo" target="_blank" title="GitLab"><i class="bi bi-gitlab text-muted"></i></a>
        <a href="https://www.linkedin.com/in/javier-alejandro-beltran-montiel-3172222b1/" target="_blank" title="LinkedIn"><i class="bi bi-linkedin text-muted"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "cover.png", alt: "ThreadHub", height: "40", width: "auto" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to "My Posts", blogs_myblogs_path, class: "navbar-brand" %>
          <% if current_user.admin? %>
            <div class="dropdown navbar-brand">
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" id="blogMenu" data-bs-toggle="dropdown" data-turbo="false" aria-expanded="false">
                Admin Panel
              </button>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="blogMenu">
                <li>
                  <%= link_to "Admin Blogs", admin_dashboard_path, class:"dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Admin Users", admin_users_path, class:"dropdown-item" %>
                </li>
              </ul>
            </div>
          <% end %>
          <div class="dropdown navbar-brand">
            <button class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" id="blogMenu" data-bs-toggle="dropdown" data-turbo="false" aria-expanded="false">
              Settings
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="blogMenu">
              <li>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              </li>
            </ul>
          </div>
          <li class="nav-item">
            <span class="navbar-text me-3">Welcome, <%= current_user.user_name %></span>
          </li>
          <li class="nav-item">
            <%= button_to "Log Out", destroy_user_session_path, method: 'delete', class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "ThreadHub" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
    <%#  Bootstrap %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%# Favicon %>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon-32x32.png' %>">
    <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'apple-touch-icon.png' %>">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", media: "all" %>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <%= render partial:"layouts/navbar"%>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <main class="flex-grow-1 container py-4">
      <%= yield %>
    </div>
  </main>
  <%= render partial:"layouts/footer"%>
  <%# Bootstrap JS + Popper  %>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>